/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReceiptRouteImport } from './routes/_authenticated/receipt'
import { Route as AuthenticatedQuotationRouteImport } from './routes/_authenticated/quotation'
import { Route as AuthenticatedPayslipRouteImport } from './routes/_authenticated/payslip'
import { Route as AuthenticatedInvoiceRouteImport } from './routes/_authenticated/invoice'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCvBuilderRouteImport } from './routes/_authenticated/cv-builder'
import { Route as AuthenticatedCoverLetterRouteImport } from './routes/_authenticated/cover-letter'
import { Route as AuthenticatedCalculatorsRouteImport } from './routes/_authenticated/calculators'
import { Route as AuthenticatedBusinessNameGeneratorRouteImport } from './routes/_authenticated/business-name-generator'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceiptRoute = AuthenticatedReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationRoute = AuthenticatedQuotationRouteImport.update({
  id: '/quotation',
  path: '/quotation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayslipRoute = AuthenticatedPayslipRouteImport.update({
  id: '/payslip',
  path: '/payslip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoiceRoute = AuthenticatedInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCvBuilderRoute = AuthenticatedCvBuilderRouteImport.update({
  id: '/cv-builder',
  path: '/cv-builder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoverLetterRoute =
  AuthenticatedCoverLetterRouteImport.update({
    id: '/cover-letter',
    path: '/cover-letter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalculatorsRoute =
  AuthenticatedCalculatorsRouteImport.update({
    id: '/calculators',
    path: '/calculators',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessNameGeneratorRoute =
  AuthenticatedBusinessNameGeneratorRouteImport.update({
    id: '/business-name-generator',
    path: '/business-name-generator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/business-name-generator': typeof AuthenticatedBusinessNameGeneratorRoute
  '/calculators': typeof AuthenticatedCalculatorsRoute
  '/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/cv-builder': typeof AuthenticatedCvBuilderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoice': typeof AuthenticatedInvoiceRoute
  '/payslip': typeof AuthenticatedPayslipRoute
  '/quotation': typeof AuthenticatedQuotationRoute
  '/receipt': typeof AuthenticatedReceiptRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/business-name-generator': typeof AuthenticatedBusinessNameGeneratorRoute
  '/calculators': typeof AuthenticatedCalculatorsRoute
  '/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/cv-builder': typeof AuthenticatedCvBuilderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoice': typeof AuthenticatedInvoiceRoute
  '/payslip': typeof AuthenticatedPayslipRoute
  '/quotation': typeof AuthenticatedQuotationRoute
  '/receipt': typeof AuthenticatedReceiptRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/business-name-generator': typeof AuthenticatedBusinessNameGeneratorRoute
  '/_authenticated/calculators': typeof AuthenticatedCalculatorsRoute
  '/_authenticated/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/_authenticated/cv-builder': typeof AuthenticatedCvBuilderRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoice': typeof AuthenticatedInvoiceRoute
  '/_authenticated/payslip': typeof AuthenticatedPayslipRoute
  '/_authenticated/quotation': typeof AuthenticatedQuotationRoute
  '/_authenticated/receipt': typeof AuthenticatedReceiptRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/ai-assistant'
    | '/business-name-generator'
    | '/calculators'
    | '/cover-letter'
    | '/cv-builder'
    | '/dashboard'
    | '/invoice'
    | '/payslip'
    | '/quotation'
    | '/receipt'
    | '/settings'
    | '/subscription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/ai-assistant'
    | '/business-name-generator'
    | '/calculators'
    | '/cover-letter'
    | '/cv-builder'
    | '/dashboard'
    | '/invoice'
    | '/payslip'
    | '/quotation'
    | '/receipt'
    | '/settings'
    | '/subscription'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/business-name-generator'
    | '/_authenticated/calculators'
    | '/_authenticated/cover-letter'
    | '/_authenticated/cv-builder'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoice'
    | '/_authenticated/payslip'
    | '/_authenticated/quotation'
    | '/_authenticated/receipt'
    | '/_authenticated/settings'
    | '/_authenticated/subscription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipt': {
      id: '/_authenticated/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof AuthenticatedReceiptRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotation': {
      id: '/_authenticated/quotation'
      path: '/quotation'
      fullPath: '/quotation'
      preLoaderRoute: typeof AuthenticatedQuotationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payslip': {
      id: '/_authenticated/payslip'
      path: '/payslip'
      fullPath: '/payslip'
      preLoaderRoute: typeof AuthenticatedPayslipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoice': {
      id: '/_authenticated/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof AuthenticatedInvoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cv-builder': {
      id: '/_authenticated/cv-builder'
      path: '/cv-builder'
      fullPath: '/cv-builder'
      preLoaderRoute: typeof AuthenticatedCvBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cover-letter': {
      id: '/_authenticated/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof AuthenticatedCoverLetterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculators': {
      id: '/_authenticated/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof AuthenticatedCalculatorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-name-generator': {
      id: '/_authenticated/business-name-generator'
      path: '/business-name-generator'
      fullPath: '/business-name-generator'
      preLoaderRoute: typeof AuthenticatedBusinessNameGeneratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedBusinessNameGeneratorRoute: typeof AuthenticatedBusinessNameGeneratorRoute
  AuthenticatedCalculatorsRoute: typeof AuthenticatedCalculatorsRoute
  AuthenticatedCoverLetterRoute: typeof AuthenticatedCoverLetterRoute
  AuthenticatedCvBuilderRoute: typeof AuthenticatedCvBuilderRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoiceRoute: typeof AuthenticatedInvoiceRoute
  AuthenticatedPayslipRoute: typeof AuthenticatedPayslipRoute
  AuthenticatedQuotationRoute: typeof AuthenticatedQuotationRoute
  AuthenticatedReceiptRoute: typeof AuthenticatedReceiptRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedBusinessNameGeneratorRoute:
    AuthenticatedBusinessNameGeneratorRoute,
  AuthenticatedCalculatorsRoute: AuthenticatedCalculatorsRoute,
  AuthenticatedCoverLetterRoute: AuthenticatedCoverLetterRoute,
  AuthenticatedCvBuilderRoute: AuthenticatedCvBuilderRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoiceRoute: AuthenticatedInvoiceRoute,
  AuthenticatedPayslipRoute: AuthenticatedPayslipRoute,
  AuthenticatedQuotationRoute: AuthenticatedQuotationRoute,
  AuthenticatedReceiptRoute: AuthenticatedReceiptRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
