/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReceiptRouteImport } from './routes/_authenticated/receipt'
import { Route as AuthenticatedQuotationRouteImport } from './routes/_authenticated/quotation'
import { Route as AuthenticatedPdfToWordRouteImport } from './routes/_authenticated/pdf-to-word'
import { Route as AuthenticatedPayslipRouteImport } from './routes/_authenticated/payslip'
import { Route as AuthenticatedInvoiceRouteImport } from './routes/_authenticated/invoice'
import { Route as AuthenticatedFilesRouteImport } from './routes/_authenticated/files'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCvBuilderRouteImport } from './routes/_authenticated/cv-builder'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCoverLetterRouteImport } from './routes/_authenticated/cover-letter'
import { Route as AuthenticatedCompanyRouteImport } from './routes/_authenticated/company'
import { Route as AuthenticatedCalculatorsRouteImport } from './routes/_authenticated/calculators'
import { Route as AuthenticatedBusinessNameGeneratorRouteImport } from './routes/_authenticated/business-name-generator'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedReceiptIndexRouteImport } from './routes/_authenticated/receipt.index'
import { Route as AuthenticatedQuotationIndexRouteImport } from './routes/_authenticated/quotation.index'
import { Route as AuthenticatedInvoiceIndexRouteImport } from './routes/_authenticated/invoice.index'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as AuthenticatedReceiptNewRouteImport } from './routes/_authenticated/receipt.new'
import { Route as AuthenticatedQuotationNewRouteImport } from './routes/_authenticated/quotation.new'
import { Route as AuthenticatedInvoiceNewRouteImport } from './routes/_authenticated/invoice.new'
import { Route as AuthenticatedReceiptIdIndexRouteImport } from './routes/_authenticated/receipt.$id.index'
import { Route as AuthenticatedQuotationIdIndexRouteImport } from './routes/_authenticated/quotation.$id.index'
import { Route as AuthenticatedInvoiceIdIndexRouteImport } from './routes/_authenticated/invoice.$id.index'
import { Route as ApiPublicShareTokenRouteImport } from './routes/api/public/share.$token'
import { Route as AuthenticatedReceiptIdEditRouteImport } from './routes/_authenticated/receipt.$id.edit'
import { Route as AuthenticatedQuotationIdEditRouteImport } from './routes/_authenticated/quotation.$id.edit'
import { Route as AuthenticatedInvoiceIdEditRouteImport } from './routes/_authenticated/invoice.$id.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceiptRoute = AuthenticatedReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationRoute = AuthenticatedQuotationRouteImport.update({
  id: '/quotation',
  path: '/quotation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPdfToWordRoute = AuthenticatedPdfToWordRouteImport.update({
  id: '/pdf-to-word',
  path: '/pdf-to-word',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayslipRoute = AuthenticatedPayslipRouteImport.update({
  id: '/payslip',
  path: '/payslip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoiceRoute = AuthenticatedInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilesRoute = AuthenticatedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCvBuilderRoute = AuthenticatedCvBuilderRouteImport.update({
  id: '/cv-builder',
  path: '/cv-builder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoverLetterRoute =
  AuthenticatedCoverLetterRouteImport.update({
    id: '/cover-letter',
    path: '/cover-letter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompanyRoute = AuthenticatedCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalculatorsRoute =
  AuthenticatedCalculatorsRouteImport.update({
    id: '/calculators',
    path: '/calculators',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessNameGeneratorRoute =
  AuthenticatedBusinessNameGeneratorRouteImport.update({
    id: '/business-name-generator',
    path: '/business-name-generator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceiptIndexRoute =
  AuthenticatedReceiptIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReceiptRoute,
  } as any)
const AuthenticatedQuotationIndexRoute =
  AuthenticatedQuotationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedQuotationRoute,
  } as any)
const AuthenticatedInvoiceIndexRoute =
  AuthenticatedInvoiceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInvoiceRoute,
  } as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReceiptNewRoute = AuthenticatedReceiptNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedReceiptRoute,
} as any)
const AuthenticatedQuotationNewRoute =
  AuthenticatedQuotationNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedQuotationRoute,
  } as any)
const AuthenticatedInvoiceNewRoute = AuthenticatedInvoiceNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedInvoiceRoute,
} as any)
const AuthenticatedReceiptIdIndexRoute =
  AuthenticatedReceiptIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AuthenticatedReceiptRoute,
  } as any)
const AuthenticatedQuotationIdIndexRoute =
  AuthenticatedQuotationIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AuthenticatedQuotationRoute,
  } as any)
const AuthenticatedInvoiceIdIndexRoute =
  AuthenticatedInvoiceIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AuthenticatedInvoiceRoute,
  } as any)
const ApiPublicShareTokenRoute = ApiPublicShareTokenRouteImport.update({
  id: '/api/public/share/$token',
  path: '/api/public/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReceiptIdEditRoute =
  AuthenticatedReceiptIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedReceiptRoute,
  } as any)
const AuthenticatedQuotationIdEditRoute =
  AuthenticatedQuotationIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedQuotationRoute,
  } as any)
const AuthenticatedInvoiceIdEditRoute =
  AuthenticatedInvoiceIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedInvoiceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/business-name-generator': typeof AuthenticatedBusinessNameGeneratorRoute
  '/calculators': typeof AuthenticatedCalculatorsRoute
  '/company': typeof AuthenticatedCompanyRoute
  '/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/cv-builder': typeof AuthenticatedCvBuilderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/files': typeof AuthenticatedFilesRoute
  '/invoice': typeof AuthenticatedInvoiceRouteWithChildren
  '/payslip': typeof AuthenticatedPayslipRoute
  '/pdf-to-word': typeof AuthenticatedPdfToWordRoute
  '/quotation': typeof AuthenticatedQuotationRouteWithChildren
  '/receipt': typeof AuthenticatedReceiptRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/share/$token': typeof ShareTokenRoute
  '/invoice/new': typeof AuthenticatedInvoiceNewRoute
  '/quotation/new': typeof AuthenticatedQuotationNewRoute
  '/receipt/new': typeof AuthenticatedReceiptNewRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/invoice/': typeof AuthenticatedInvoiceIndexRoute
  '/quotation/': typeof AuthenticatedQuotationIndexRoute
  '/receipt/': typeof AuthenticatedReceiptIndexRoute
  '/invoice/$id/edit': typeof AuthenticatedInvoiceIdEditRoute
  '/quotation/$id/edit': typeof AuthenticatedQuotationIdEditRoute
  '/receipt/$id/edit': typeof AuthenticatedReceiptIdEditRoute
  '/api/public/share/$token': typeof ApiPublicShareTokenRoute
  '/invoice/$id/': typeof AuthenticatedInvoiceIdIndexRoute
  '/quotation/$id/': typeof AuthenticatedQuotationIdIndexRoute
  '/receipt/$id/': typeof AuthenticatedReceiptIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/business-name-generator': typeof AuthenticatedBusinessNameGeneratorRoute
  '/calculators': typeof AuthenticatedCalculatorsRoute
  '/company': typeof AuthenticatedCompanyRoute
  '/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/cv-builder': typeof AuthenticatedCvBuilderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/files': typeof AuthenticatedFilesRoute
  '/payslip': typeof AuthenticatedPayslipRoute
  '/pdf-to-word': typeof AuthenticatedPdfToWordRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/share/$token': typeof ShareTokenRoute
  '/invoice/new': typeof AuthenticatedInvoiceNewRoute
  '/quotation/new': typeof AuthenticatedQuotationNewRoute
  '/receipt/new': typeof AuthenticatedReceiptNewRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/invoice': typeof AuthenticatedInvoiceIndexRoute
  '/quotation': typeof AuthenticatedQuotationIndexRoute
  '/receipt': typeof AuthenticatedReceiptIndexRoute
  '/invoice/$id/edit': typeof AuthenticatedInvoiceIdEditRoute
  '/quotation/$id/edit': typeof AuthenticatedQuotationIdEditRoute
  '/receipt/$id/edit': typeof AuthenticatedReceiptIdEditRoute
  '/api/public/share/$token': typeof ApiPublicShareTokenRoute
  '/invoice/$id': typeof AuthenticatedInvoiceIdIndexRoute
  '/quotation/$id': typeof AuthenticatedQuotationIdIndexRoute
  '/receipt/$id': typeof AuthenticatedReceiptIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/business-name-generator': typeof AuthenticatedBusinessNameGeneratorRoute
  '/_authenticated/calculators': typeof AuthenticatedCalculatorsRoute
  '/_authenticated/company': typeof AuthenticatedCompanyRoute
  '/_authenticated/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/cv-builder': typeof AuthenticatedCvBuilderRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/files': typeof AuthenticatedFilesRoute
  '/_authenticated/invoice': typeof AuthenticatedInvoiceRouteWithChildren
  '/_authenticated/payslip': typeof AuthenticatedPayslipRoute
  '/_authenticated/pdf-to-word': typeof AuthenticatedPdfToWordRoute
  '/_authenticated/quotation': typeof AuthenticatedQuotationRouteWithChildren
  '/_authenticated/receipt': typeof AuthenticatedReceiptRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authenticated/invoice/new': typeof AuthenticatedInvoiceNewRoute
  '/_authenticated/quotation/new': typeof AuthenticatedQuotationNewRoute
  '/_authenticated/receipt/new': typeof AuthenticatedReceiptNewRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/_authenticated/invoice/': typeof AuthenticatedInvoiceIndexRoute
  '/_authenticated/quotation/': typeof AuthenticatedQuotationIndexRoute
  '/_authenticated/receipt/': typeof AuthenticatedReceiptIndexRoute
  '/_authenticated/invoice/$id/edit': typeof AuthenticatedInvoiceIdEditRoute
  '/_authenticated/quotation/$id/edit': typeof AuthenticatedQuotationIdEditRoute
  '/_authenticated/receipt/$id/edit': typeof AuthenticatedReceiptIdEditRoute
  '/api/public/share/$token': typeof ApiPublicShareTokenRoute
  '/_authenticated/invoice/$id/': typeof AuthenticatedInvoiceIdIndexRoute
  '/_authenticated/quotation/$id/': typeof AuthenticatedQuotationIdIndexRoute
  '/_authenticated/receipt/$id/': typeof AuthenticatedReceiptIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/ai-assistant'
    | '/business-name-generator'
    | '/calculators'
    | '/company'
    | '/cover-letter'
    | '/customers'
    | '/cv-builder'
    | '/dashboard'
    | '/files'
    | '/invoice'
    | '/payslip'
    | '/pdf-to-word'
    | '/quotation'
    | '/receipt'
    | '/settings'
    | '/subscription'
    | '/share/$token'
    | '/invoice/new'
    | '/quotation/new'
    | '/receipt/new'
    | '/api/ai/chat'
    | '/invoice/'
    | '/quotation/'
    | '/receipt/'
    | '/invoice/$id/edit'
    | '/quotation/$id/edit'
    | '/receipt/$id/edit'
    | '/api/public/share/$token'
    | '/invoice/$id/'
    | '/quotation/$id/'
    | '/receipt/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/ai-assistant'
    | '/business-name-generator'
    | '/calculators'
    | '/company'
    | '/cover-letter'
    | '/customers'
    | '/cv-builder'
    | '/dashboard'
    | '/files'
    | '/payslip'
    | '/pdf-to-word'
    | '/settings'
    | '/subscription'
    | '/share/$token'
    | '/invoice/new'
    | '/quotation/new'
    | '/receipt/new'
    | '/api/ai/chat'
    | '/invoice'
    | '/quotation'
    | '/receipt'
    | '/invoice/$id/edit'
    | '/quotation/$id/edit'
    | '/receipt/$id/edit'
    | '/api/public/share/$token'
    | '/invoice/$id'
    | '/quotation/$id'
    | '/receipt/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/business-name-generator'
    | '/_authenticated/calculators'
    | '/_authenticated/company'
    | '/_authenticated/cover-letter'
    | '/_authenticated/customers'
    | '/_authenticated/cv-builder'
    | '/_authenticated/dashboard'
    | '/_authenticated/files'
    | '/_authenticated/invoice'
    | '/_authenticated/payslip'
    | '/_authenticated/pdf-to-word'
    | '/_authenticated/quotation'
    | '/_authenticated/receipt'
    | '/_authenticated/settings'
    | '/_authenticated/subscription'
    | '/share/$token'
    | '/_authenticated/invoice/new'
    | '/_authenticated/quotation/new'
    | '/_authenticated/receipt/new'
    | '/api/ai/chat'
    | '/_authenticated/invoice/'
    | '/_authenticated/quotation/'
    | '/_authenticated/receipt/'
    | '/_authenticated/invoice/$id/edit'
    | '/_authenticated/quotation/$id/edit'
    | '/_authenticated/receipt/$id/edit'
    | '/api/public/share/$token'
    | '/_authenticated/invoice/$id/'
    | '/_authenticated/quotation/$id/'
    | '/_authenticated/receipt/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiPublicShareTokenRoute: typeof ApiPublicShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipt': {
      id: '/_authenticated/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof AuthenticatedReceiptRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotation': {
      id: '/_authenticated/quotation'
      path: '/quotation'
      fullPath: '/quotation'
      preLoaderRoute: typeof AuthenticatedQuotationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pdf-to-word': {
      id: '/_authenticated/pdf-to-word'
      path: '/pdf-to-word'
      fullPath: '/pdf-to-word'
      preLoaderRoute: typeof AuthenticatedPdfToWordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payslip': {
      id: '/_authenticated/payslip'
      path: '/payslip'
      fullPath: '/payslip'
      preLoaderRoute: typeof AuthenticatedPayslipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoice': {
      id: '/_authenticated/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof AuthenticatedInvoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/files': {
      id: '/_authenticated/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedFilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cv-builder': {
      id: '/_authenticated/cv-builder'
      path: '/cv-builder'
      fullPath: '/cv-builder'
      preLoaderRoute: typeof AuthenticatedCvBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cover-letter': {
      id: '/_authenticated/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof AuthenticatedCoverLetterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company': {
      id: '/_authenticated/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthenticatedCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculators': {
      id: '/_authenticated/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof AuthenticatedCalculatorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-name-generator': {
      id: '/_authenticated/business-name-generator'
      path: '/business-name-generator'
      fullPath: '/business-name-generator'
      preLoaderRoute: typeof AuthenticatedBusinessNameGeneratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipt/': {
      id: '/_authenticated/receipt/'
      path: '/'
      fullPath: '/receipt/'
      preLoaderRoute: typeof AuthenticatedReceiptIndexRouteImport
      parentRoute: typeof AuthenticatedReceiptRoute
    }
    '/_authenticated/quotation/': {
      id: '/_authenticated/quotation/'
      path: '/'
      fullPath: '/quotation/'
      preLoaderRoute: typeof AuthenticatedQuotationIndexRouteImport
      parentRoute: typeof AuthenticatedQuotationRoute
    }
    '/_authenticated/invoice/': {
      id: '/_authenticated/invoice/'
      path: '/'
      fullPath: '/invoice/'
      preLoaderRoute: typeof AuthenticatedInvoiceIndexRouteImport
      parentRoute: typeof AuthenticatedInvoiceRoute
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/receipt/new': {
      id: '/_authenticated/receipt/new'
      path: '/new'
      fullPath: '/receipt/new'
      preLoaderRoute: typeof AuthenticatedReceiptNewRouteImport
      parentRoute: typeof AuthenticatedReceiptRoute
    }
    '/_authenticated/quotation/new': {
      id: '/_authenticated/quotation/new'
      path: '/new'
      fullPath: '/quotation/new'
      preLoaderRoute: typeof AuthenticatedQuotationNewRouteImport
      parentRoute: typeof AuthenticatedQuotationRoute
    }
    '/_authenticated/invoice/new': {
      id: '/_authenticated/invoice/new'
      path: '/new'
      fullPath: '/invoice/new'
      preLoaderRoute: typeof AuthenticatedInvoiceNewRouteImport
      parentRoute: typeof AuthenticatedInvoiceRoute
    }
    '/_authenticated/receipt/$id/': {
      id: '/_authenticated/receipt/$id/'
      path: '/$id'
      fullPath: '/receipt/$id/'
      preLoaderRoute: typeof AuthenticatedReceiptIdIndexRouteImport
      parentRoute: typeof AuthenticatedReceiptRoute
    }
    '/_authenticated/quotation/$id/': {
      id: '/_authenticated/quotation/$id/'
      path: '/$id'
      fullPath: '/quotation/$id/'
      preLoaderRoute: typeof AuthenticatedQuotationIdIndexRouteImport
      parentRoute: typeof AuthenticatedQuotationRoute
    }
    '/_authenticated/invoice/$id/': {
      id: '/_authenticated/invoice/$id/'
      path: '/$id'
      fullPath: '/invoice/$id/'
      preLoaderRoute: typeof AuthenticatedInvoiceIdIndexRouteImport
      parentRoute: typeof AuthenticatedInvoiceRoute
    }
    '/api/public/share/$token': {
      id: '/api/public/share/$token'
      path: '/api/public/share/$token'
      fullPath: '/api/public/share/$token'
      preLoaderRoute: typeof ApiPublicShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/receipt/$id/edit': {
      id: '/_authenticated/receipt/$id/edit'
      path: '/$id/edit'
      fullPath: '/receipt/$id/edit'
      preLoaderRoute: typeof AuthenticatedReceiptIdEditRouteImport
      parentRoute: typeof AuthenticatedReceiptRoute
    }
    '/_authenticated/quotation/$id/edit': {
      id: '/_authenticated/quotation/$id/edit'
      path: '/$id/edit'
      fullPath: '/quotation/$id/edit'
      preLoaderRoute: typeof AuthenticatedQuotationIdEditRouteImport
      parentRoute: typeof AuthenticatedQuotationRoute
    }
    '/_authenticated/invoice/$id/edit': {
      id: '/_authenticated/invoice/$id/edit'
      path: '/$id/edit'
      fullPath: '/invoice/$id/edit'
      preLoaderRoute: typeof AuthenticatedInvoiceIdEditRouteImport
      parentRoute: typeof AuthenticatedInvoiceRoute
    }
  }
}

interface AuthenticatedInvoiceRouteChildren {
  AuthenticatedInvoiceNewRoute: typeof AuthenticatedInvoiceNewRoute
  AuthenticatedInvoiceIndexRoute: typeof AuthenticatedInvoiceIndexRoute
  AuthenticatedInvoiceIdEditRoute: typeof AuthenticatedInvoiceIdEditRoute
  AuthenticatedInvoiceIdIndexRoute: typeof AuthenticatedInvoiceIdIndexRoute
}

const AuthenticatedInvoiceRouteChildren: AuthenticatedInvoiceRouteChildren = {
  AuthenticatedInvoiceNewRoute: AuthenticatedInvoiceNewRoute,
  AuthenticatedInvoiceIndexRoute: AuthenticatedInvoiceIndexRoute,
  AuthenticatedInvoiceIdEditRoute: AuthenticatedInvoiceIdEditRoute,
  AuthenticatedInvoiceIdIndexRoute: AuthenticatedInvoiceIdIndexRoute,
}

const AuthenticatedInvoiceRouteWithChildren =
  AuthenticatedInvoiceRoute._addFileChildren(AuthenticatedInvoiceRouteChildren)

interface AuthenticatedQuotationRouteChildren {
  AuthenticatedQuotationNewRoute: typeof AuthenticatedQuotationNewRoute
  AuthenticatedQuotationIndexRoute: typeof AuthenticatedQuotationIndexRoute
  AuthenticatedQuotationIdEditRoute: typeof AuthenticatedQuotationIdEditRoute
  AuthenticatedQuotationIdIndexRoute: typeof AuthenticatedQuotationIdIndexRoute
}

const AuthenticatedQuotationRouteChildren: AuthenticatedQuotationRouteChildren =
  {
    AuthenticatedQuotationNewRoute: AuthenticatedQuotationNewRoute,
    AuthenticatedQuotationIndexRoute: AuthenticatedQuotationIndexRoute,
    AuthenticatedQuotationIdEditRoute: AuthenticatedQuotationIdEditRoute,
    AuthenticatedQuotationIdIndexRoute: AuthenticatedQuotationIdIndexRoute,
  }

const AuthenticatedQuotationRouteWithChildren =
  AuthenticatedQuotationRoute._addFileChildren(
    AuthenticatedQuotationRouteChildren,
  )

interface AuthenticatedReceiptRouteChildren {
  AuthenticatedReceiptNewRoute: typeof AuthenticatedReceiptNewRoute
  AuthenticatedReceiptIndexRoute: typeof AuthenticatedReceiptIndexRoute
  AuthenticatedReceiptIdEditRoute: typeof AuthenticatedReceiptIdEditRoute
  AuthenticatedReceiptIdIndexRoute: typeof AuthenticatedReceiptIdIndexRoute
}

const AuthenticatedReceiptRouteChildren: AuthenticatedReceiptRouteChildren = {
  AuthenticatedReceiptNewRoute: AuthenticatedReceiptNewRoute,
  AuthenticatedReceiptIndexRoute: AuthenticatedReceiptIndexRoute,
  AuthenticatedReceiptIdEditRoute: AuthenticatedReceiptIdEditRoute,
  AuthenticatedReceiptIdIndexRoute: AuthenticatedReceiptIdIndexRoute,
}

const AuthenticatedReceiptRouteWithChildren =
  AuthenticatedReceiptRoute._addFileChildren(AuthenticatedReceiptRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedBusinessNameGeneratorRoute: typeof AuthenticatedBusinessNameGeneratorRoute
  AuthenticatedCalculatorsRoute: typeof AuthenticatedCalculatorsRoute
  AuthenticatedCompanyRoute: typeof AuthenticatedCompanyRoute
  AuthenticatedCoverLetterRoute: typeof AuthenticatedCoverLetterRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedCvBuilderRoute: typeof AuthenticatedCvBuilderRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFilesRoute: typeof AuthenticatedFilesRoute
  AuthenticatedInvoiceRoute: typeof AuthenticatedInvoiceRouteWithChildren
  AuthenticatedPayslipRoute: typeof AuthenticatedPayslipRoute
  AuthenticatedPdfToWordRoute: typeof AuthenticatedPdfToWordRoute
  AuthenticatedQuotationRoute: typeof AuthenticatedQuotationRouteWithChildren
  AuthenticatedReceiptRoute: typeof AuthenticatedReceiptRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedBusinessNameGeneratorRoute:
    AuthenticatedBusinessNameGeneratorRoute,
  AuthenticatedCalculatorsRoute: AuthenticatedCalculatorsRoute,
  AuthenticatedCompanyRoute: AuthenticatedCompanyRoute,
  AuthenticatedCoverLetterRoute: AuthenticatedCoverLetterRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedCvBuilderRoute: AuthenticatedCvBuilderRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFilesRoute: AuthenticatedFilesRoute,
  AuthenticatedInvoiceRoute: AuthenticatedInvoiceRouteWithChildren,
  AuthenticatedPayslipRoute: AuthenticatedPayslipRoute,
  AuthenticatedPdfToWordRoute: AuthenticatedPdfToWordRoute,
  AuthenticatedQuotationRoute: AuthenticatedQuotationRouteWithChildren,
  AuthenticatedReceiptRoute: AuthenticatedReceiptRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiPublicShareTokenRoute: ApiPublicShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
